apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 3
  selector:
    matchLabels:
      app: apps
  template:
    metadata:
      labels:
        app: apps
    spec:
      containers:
        - image: nginx:1.13
          name: nginx
          resources:
            requests:
              cpu: 20
              memory: 300Mi
            limits:
              cpu: 20
              memory: 300Mi
          ports:
            - containerPort: 9843
